import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

// TanStack Start picks up this `getRouter` factory to build a router instance
// per request (SSR) and once on the client. `routeTree.gen.ts` is generated by
// the TanStack Start vite plugin on `vite dev` / `vite build`.
export function getRouter() {
  const router = createRouter({
    routeTree,
    scrollRestoration: true,
  });

  return router;
}

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof getRouter>;
  }
}
